<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-27T17:57:09 GMT+07:00" name="Default suite" finished-at="2025-05-27T17:57:40 GMT+07:00" duration-ms="30877">
    <groups>
    </groups>
    <test started-at="2025-05-27T17:57:09 GMT+07:00" name="Default test" finished-at="2025-05-27T17:57:40 GMT+07:00" duration-ms="30877">
      <class name="tests.ScreenshotTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.ScreenshotTest@3bae64d0]" started-at="2025-05-27T17:57:09 GMT+07:00" name="setup" finished-at="2025-05-27T17:57:22 GMT+07:00" duration-ms="12310" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:10, instance:tests.ScreenshotTest@3bae64d0]" started-at="2025-05-27T17:57:22 GMT+07:00" name="login" description="Open website and log in" finished-at="2025-05-27T17:57:38 GMT+07:00" duration-ms="16006" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="captureScreenshot(org.testng.ITestResult)[pri:0, instance:tests.ScreenshotTest@3bae64d0]" started-at="2025-05-27T17:57:38 GMT+07:00" name="captureScreenshot" finished-at="2025-05-27T17:57:38 GMT+07:00" duration-ms="224" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=SUCCESS method=ScreenshotTest.login()[pri:10, instance:tests.ScreenshotTest@3bae64d0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureScreenshot -->
        <test-method signature="thisStepIsFailed()[pri:20, instance:tests.ScreenshotTest@3bae64d0]" started-at="2025-05-27T17:57:38 GMT+07:00" name="thisStepIsFailed" finished-at="2025-05-27T17:57:39 GMT+07:00" duration-ms="52" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.ScreenshotTest.thisStepIsFailed(ScreenshotTest.java:166)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thisStepIsFailed -->
        <test-method is-config="true" signature="captureScreenshot(org.testng.ITestResult)[pri:0, instance:tests.ScreenshotTest@3bae64d0]" started-at="2025-05-27T17:57:39 GMT+07:00" name="captureScreenshot" finished-at="2025-05-27T17:57:40 GMT+07:00" duration-ms="1134" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=thisStepIsFailed status=FAILURE method=ScreenshotTest.thisStepIsFailed()[pri:20, instance:tests.ScreenshotTest@3bae64d0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureScreenshot -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.ScreenshotTest@3bae64d0]" started-at="2025-05-27T17:57:40 GMT+07:00" name="tearDown" finished-at="2025-05-27T17:57:40 GMT+07:00" duration-ms="510" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.ScreenshotTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
